# List compiled from
# https://en.wikipedia.org/wiki/Vocal_Group_Hall_of_Fame
# https://en.wikipedia.org/wiki/List_of_vocal_groups
# https://en.wikipedia.org/wiki/Category:American_vocal_groups

bands = ["The Ames Brothers",
         "The Andrews Sisters",
         "The Association",
         "The Axidentals",
         "The Bangles",
         "The Beach Boys",
         "The Boswell Sisters",
         "The Five Blind Boys of Mississippi",
         "The Golden Gate Quartet",
         "The Original Drifters",
         "The Mills Brothers",
         "The Manhattan Transfer",
         "The Platters",
         "The Ravens",
         "The Orioles",
         "The Supremes",
         "The Chordettes",
         "The Chantels",
         "The Charioteers",
         "The Chi-Lites",
         "The Clovers",
         "The Coasters",
         "The Commodores",
         "The Contours",
         "The Crew-Cuts",
         "The Dells",
         "The Delfonics",
         "The Delta Rhythm Boys",
         "The Dramatics",
         "The Dream Weavers",
         "The Dreamers",
         "The Drifters",
         "The Eagles",
         "The Eagles (rhythm and blues group)",
         "The Emotions",
         "The Five Blind Boys of Mississippi",
         "The Five Keys",
         "The Five Satins",
         "The Flamingos",
         "The Foundations",
         "The Four Aces",
         "The Four Esquires",
         "The Four Freshmen",
         "The Four Knights",
         "The Four Lads",
         "The Four Seasons",
         "The Four Tops",
         "The Gaylords",
         "The Golden Gate Quartet",
         "The Harptones",
         "The Hilltoppers",
         "The Hi-Los",
         "The Impressions",
         "The Ink Spots",
         "The Midnighters",
         "The Isley Brothers",
         "The Jackson Five",
         "The Imperials",
         "The Modernaires",
         "The Moonglows",
         "The Revelers",
         "The Spinners",
         "The Temptations",
         "The Bangles",
         "The Belmonts",
         "The Drifters",
         "The Flamingos",
         "The Teenagers",
         "The Jordanaires",
         "The Kingston Trio",
         "The Mamas &", "The Papas",
         "The Skylarks",
         "The Soul Stirrers",
         "The Bee Gees",
         "The Chordettes",
         "The Four Aces",
         "The Four Freshmen",
         "The Pips",
         "The Lennon Sisters",
         "The Lettermen",
         "The Main Ingredient",
         "The Mamas & the Papas",
         "The Manhattans",
         "The Manhattan Transfer",
         "The Marcels",
         "The Marvelettes",
         "The McGuire Sisters",
         "The Merry Macs",
         "The Midnighters",
         "The Mills Brothers",
         "The Miracles",
         "The Modernaires",
         "The Moonglows",
         "The Oak Ridge Boys",
         "The O'Jays",
         "The Original Drifters",
         "The Orioles",
         "The Peerless Quartet",
         "The Pied Pipers",
         "The Miracles",
         "The Vogues",
         "The Weavers",
         "The Chantels",
         "The Clovers",
         "The Fifth Dimension",
         "The Five Keys",
         "The Four Knights",
         "The Harptones",
         "The Americans",
         "The Marcels",
         "The Platters",
         "The Playmates",
         "The Pointer Sisters",
         "The Ravens",
         "The Revelers",
         "The Roches",
         "The Romantics",
         "The Seekers",
         "The Shirelles",
         "The Skylarks",
         "The Skyliners",
         "The Soul Stirrers",
         "The Spinners",
         "The Springfields",
         "The Statler Brothers",
         "The Stylistics",
         "The Supremes",
         "The Swan Silvertones",
         "The T-Bors",
         "The Temptations",
         "The Tokens",
         "The Valentinos",
         "The Vogues",
         "The Wanted",
         "The Weavers",
         "The Whispers"]
